# Generated by Django 5.1.6 on 2025-02-14 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Солдат',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_soldat_name_fa6927_idx')],
            },
        ),
        migrations.CreateModel(
            name='Geroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to='geroy/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geroys', to='main.soldat')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='main_geroy_id_5c94c0_idx'), models.Index(fields=['name'], name='main_geroy_name_38f281_idx'), models.Index(fields=['-created'], name='main_geroy_created_e4b453_idx')],
            },
        ),
    ]
